version: '3.8'

services:
  pokedex-app:
    container_name: pokedex_container
    build:
      context: .
      dockerfile: Dockerfile
    # Mapeo de puertos: Host:Contenedor
    ports:
      - "3000:3000"
    
    # Volúmenes para desarrollo en caliente (Hot Reload)
    volumes:
      - .:/app
      - /app/node_modules
    
    # Variables de entorno si la app las necesita
    environment:
      - NODE_ENV=development
    
    # Reiniciar automáticamente si falla
    restart: unless-stopped